java: /usr/bin/java

eagle:
    eagle: /home/wangcr/Softwares/Eagle_v2.4.1/eagle
    genetic_map_file:
        GRCh37: /home/wangcr/Softwares/Eagle_v2.4.1/tables/genetic_map_hg19_withX.txt.gz
        GRCh38: /home/wangcr/Softwares/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz

beagle:
    beagle: /home/wangcr/Softwares/beagle5.2/beagle.28Jun21.220.jar
    genetic_map_file:
        GRCh37: 
            '1': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr1.GRCh37.map
            '2': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr2.GRCh37.map
            '3': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr3.GRCh37.map
            '4': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr4.GRCh37.map
            '5': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr5.GRCh37.map
            '6': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr6.GRCh37.map
            '7': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr7.GRCh37.map
            '8': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr8.GRCh37.map
            '9': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr9.GRCh37.map
            '10': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr10.GRCh37.map
            '11': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr11.GRCh37.map
            '12': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr12.GRCh37.map
            '13': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr13.GRCh37.map
            '14': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr14.GRCh37.map
            '15': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr15.GRCh37.map
            '16': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr16.GRCh37.map
            '17': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr17.GRCh37.map
            '18': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr18.GRCh37.map
            '19': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr19.GRCh37.map
            '20': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr20.GRCh37.map
            '21': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr21.GRCh37.map
            '22': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chr22.GRCh37.map
            'X': /home/wangcr/Softwares/beagle5.2/plink.GRCh37.map/plink.chrX_par1.GRCh37.map
        GRCh38:
            '1': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr1.GRCh38.map
            '2': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr2.GRCh38.map
            '3': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr3.GRCh38.map
            '4': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr4.GRCh38.map
            '5': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr5.GRCh38.map
            '6': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr6.GRCh38.map
            '7': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr7.GRCh38.map
            '8': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr8.GRCh38.map
            '9': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr9.GRCh38.map
            '10': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr10.GRCh38.map
            '11': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr11.GRCh38.map
            '12': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr12.GRCh38.map
            '13': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr13.GRCh38.map
            '14': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr14.GRCh38.map
            '15': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr15.GRCh38.map
            '16': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr16.GRCh38.map
            '17': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr17.GRCh38.map
            '18': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr18.GRCh38.map
            '19': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr19.GRCh38.map
            '20': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr20.GRCh38.map
            '21': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr21.GRCh38.map
            '22': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chr22.GRCh38.map
            'X': /home/wangcr/Softwares/beagle5.2/plink.GRCh38.map/plink.chrX_par1.GRCh38.map
minimac:
    minimac: /usr/bin/minimac4
    reference_panel:
        1000G_P3_GRCh37:
            '1': /home/wangcr/Softwares/minimac4_reference_panel/1.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '2': /home/wangcr/Softwares/minimac4_reference_panel/2.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '3': /home/wangcr/Softwares/minimac4_reference_panel/3.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '4': /home/wangcr/Softwares/minimac4_reference_panel/4.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '5': /home/wangcr/Softwares/minimac4_reference_panel/5.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '6': /home/wangcr/Softwares/minimac4_reference_panel/6.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '7': /home/wangcr/Softwares/minimac4_reference_panel/7.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '8': /home/wangcr/Softwares/minimac4_reference_panel/8.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '9': /home/wangcr/Softwares/minimac4_reference_panel/9.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '10': /home/wangcr/Softwares/minimac4_reference_panel/10.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '11': /home/wangcr/Softwares/minimac4_reference_panel/11.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '12': /home/wangcr/Softwares/minimac4_reference_panel/12.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '13': /home/wangcr/Softwares/minimac4_reference_panel/13.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '14': /home/wangcr/Softwares/minimac4_reference_panel/14.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '15': /home/wangcr/Softwares/minimac4_reference_panel/15.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '16': /home/wangcr/Softwares/minimac4_reference_panel/16.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '17': /home/wangcr/Softwares/minimac4_reference_panel/17.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '18': /home/wangcr/Softwares/minimac4_reference_panel/18.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '19': /home/wangcr/Softwares/minimac4_reference_panel/19.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '20': /home/wangcr/Softwares/minimac4_reference_panel/20.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '21': /home/wangcr/Softwares/minimac4_reference_panel/21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            '22': /home/wangcr/Softwares/minimac4_reference_panel/22.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
            'X' : /home/wangcr/Softwares/minimac4_reference_panel/X.Non.Pseudo.Auto.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
        1000G_P3_GRCh38: ""
        BIGCS: 
            '1': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.1.m3vcf.gz
            '2': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.2.m3vcf.gz
            '3': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.3.m3vcf.gz
            '4': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.4.m3vcf.gz
            '5': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.5.m3vcf.gz
            '6': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.6.m3vcf.gz
            '7': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.7.m3vcf.gz
            '8': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.8.m3vcf.gz
            '9': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.9.m3vcf.gz
            '10': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.10.m3vcf.gz
            '11': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.11.m3vcf.gz
            '12': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.12.m3vcf.gz
            '13': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.13.m3vcf.gz
            '14': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.14.m3vcf.gz
            '15': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.15.m3vcf.gz
            '16': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.16.m3vcf.gz
            '17': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.17.m3vcf.gz
            '18': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.18.m3vcf.gz
            '19': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.19.m3vcf.gz
            '20': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.20.m3vcf.gz
            '21': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.21.m3vcf.gz
            '22': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.22.m3vcf.gz
            'X': /home/wangcr/Softwares/minimac4_reference_panel/BIGCS2/m3.X.m3vcf.gz
        CNRP_GRCh37: ""
        CNRP_GRCh38:
            '1': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.1.phased.v1.nochr.m3vcf.gz
            '2': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.2.phased.v1.nochr.m3vcf.gz
            '3': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.3.phased.v1.nochr.m3vcf.gz
            '4': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.4.phased.v1.nochr.m3vcf.gz
            '5': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.5.phased.v1.nochr.m3vcf.gz
            '6': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.6.phased.v1.nochr.m3vcf.gz
            '7': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.7.phased.v1.nochr.m3vcf.gz
            '8': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.8.phased.v1.nochr.m3vcf.gz
            '9': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.9.phased.v1.nochr.m3vcf.gz
            '10': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.10.phased.v1.nochr.m3vcf.gz
            '11': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.11.phased.v1.nochr.m3vcf.gz
            '12': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.12.phased.v1.nochr.m3vcf.gz
            '13': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.13.phased.v1.nochr.m3vcf.gz
            '14': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.14.phased.v1.nochr.m3vcf.gz
            '15': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.15.phased.v1.nochr.m3vcf.gz
            '16': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.16.phased.v1.nochr.m3vcf.gz
            '17': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.17.phased.v1.nochr.m3vcf.gz
            '18': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.18.phased.v1.nochr.m3vcf.gz
            '19': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.19.phased.v1.nochr.m3vcf.gz
            '20': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.20.phased.v1.nochr.m3vcf.gz
            '21': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.21.phased.v1.nochr.m3vcf.gz
            '22': /home/huangshujia/ngs_data_collection/10K_Chinese_Haplotypes_BGI/PhaseI_850_GRCh38/10KCN.22.phased.v1.nochr.m3vcf.gz
        test_panel_GRCh37:
            '6': /home/huangshujia/biosoft/minimac/Minimac3/test/refPanel.m3vcf.gz
